actions:
  - type: "remove"
    selector: ".ad-banner"
  - type: "replace"
    selector: "#old-header2"
    newElement: "<header id='new-header'>New Header2</header>"
  - type: "insert"
    position: "after"
    target: "body"
    element: "<footer>Footer Content</footer>"
  - type: "alter"
    oldValue: "ML"
    newValue: "AI2"
